/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasinilai;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author asus
 */
public class formnilaimahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form formnilaimahasiswa
     */
    public formnilaimahasiswa() throws SQLException {
        initComponents();
        tampilkanDataMahasiswa();
    }
    
    private void tampilkanDataMahasiswa () throws SQLException{
        try{
            String sql="SELECT * FROM tb_mahasiswa";
            PreparedStatement ps=null;
            Object [] row={"Nim", "Nama Mahasiswa", "Jenis Kelamin"};
            DefaultTableModel dtm=new DefaultTableModel(null,row);
                tabelmhs.setModel(dtm);
                jScrollPane1.setEnabled(true);
                jScrollPane1.setBorder(null);
                jScrollPane1.setViewportView( tabelmhs);
                ResultSet rs=null;
                ps=Koneksi.KoneksiDatabase().prepareStatement(sql);
                rs=ps.executeQuery();
                    while(rs.next()){
                        String nim=rs.getString(1);
                        String namamahasiswa=rs.getString(2);
                        String jeniskelamin=rs.getString(5); 
                        
                    String [] baris={nim,namamahasiswa,jeniskelamin};
                    dtm.addRow(baris);
                    } 
        }catch(Exception e){}
    }

    private void bersih (){
        cmbta.setSelectedItem("-- Pilih Tahun Akademik --");
        cmbsmt.setSelectedItem("-- Pilih Semester --");
        txtnomorindukmhs.setText("");
        txtnamamahasiswa.setText("");
        txtjeniskelamin.setText("");
        cmbmtk.setSelectedItem("-- Pilih Kode MTK --");
        txtnamamtk.setText("");
        txtsks.setText("");
        cmbnidn.setSelectedItem("-- Pilih NIDN --");
        txtdosen.setText("");
        txtcaridatamhs.setText("");
        txtcarinilai.setText("");
        
    }
    
    private void proses (){
        if(txtnilaiangka.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Silahkan masukan data nilai akhir");        
        }
        else
        {
            Double nilaiangka;
            String nilaihuruf, keterangan;
            Integer bobot;
            nilaiangka=Double.parseDouble(txtnilaiangka.getText());
            
                if ((nilaiangka >= 80) && (nilaiangka <= 100))
                    
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcarinilai = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbta = new javax.swing.JComboBox<>();
        cmbnidn = new javax.swing.JComboBox<>();
        txtdosen = new javax.swing.JTextField();
        txtnamamahasiswa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelmhs = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cmbsmt = new javax.swing.JComboBox<>();
        cmbmtk = new javax.swing.JComboBox<>();
        txtnomorindukmhs = new javax.swing.JTextField();
        txtketerangan = new javax.swing.JTextField();
        txtsks = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtnamamtk = new javax.swing.JTextField();
        txtnilaiangka = new javax.swing.JTextField();
        txtnilaihuruf = new javax.swing.JTextField();
        txtbobot = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelnilai = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtjeniskelamin = new javax.swing.JTextField();
        txtcaridatamhs = new javax.swing.JTextField();
        btnproses = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Form Input Data Nilai");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Cari data Nilai Mahasiswa");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 760, -1, -1));

        txtcarinilai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtcarinilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcarinilaiActionPerformed(evt);
            }
        });
        getContentPane().add(txtcarinilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 750, 230, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Dosen");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Semester");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("NIM");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Nama Mahasiswa");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        cmbta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Tahun Akademik --", "2016/2017", "2017/2018", "2019/2020", "2020/2021", "2021/2022", "2022/2023", "2023/2024", "2024/2025", " " }));
        getContentPane().add(cmbta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        cmbnidn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbnidn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih NIDN --", "DSN01", "DSN02", "DSN03", "DSN04", "DSN05", "DSN06", "DSN07", "DSN08", "DSN09", "DSN10" }));
        getContentPane().add(cmbnidn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, -1, -1));

        txtdosen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdosenActionPerformed(evt);
            }
        });
        getContentPane().add(txtdosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 240, 30));

        txtnamamahasiswa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnamamahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamamahasiswaActionPerformed(evt);
            }
        });
        getContentPane().add(txtnamamahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 330, -1));

        tabelmhs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelmhs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 490, 330));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Tahun Akademik");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Keterangan");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 210, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Nama Mata Kuliah");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("SKS");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("NIDN");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        cmbsmt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbsmt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Semester --", "Ganjil", "Genap" }));
        getContentPane().add(cmbsmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        cmbmtk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbmtk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kode MTK --", "MTK 001", "MTK 002", "MTK 003", "MTK 004", "MTK 005", "MTK 006", "MTK 007", "MTK 008", "MTK 009", "MTK 010", " " }));
        getContentPane().add(cmbmtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, -1, -1));

        txtnomorindukmhs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnomorindukmhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomorindukmhsActionPerformed(evt);
            }
        });
        getContentPane().add(txtnomorindukmhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, -1));

        txtketerangan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtketerangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtketeranganActionPerformed(evt);
            }
        });
        getContentPane().add(txtketerangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 210, 270, -1));

        txtsks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtsks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsksActionPerformed(evt);
            }
        });
        getContentPane().add(txtsks, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 60, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Kode Mata Kuliah");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Nilai Angka");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 90, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Nilai Huruf");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 130, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Bobot");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 170, -1, -1));

        txtnamamtk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnamamtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamamtkActionPerformed(evt);
            }
        });
        getContentPane().add(txtnamamtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 200, 30));

        txtnilaiangka.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtnilaiangka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnilaiangkaActionPerformed(evt);
            }
        });
        getContentPane().add(txtnilaiangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 90, 110, -1));

        txtnilaihuruf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtnilaihuruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnilaihurufActionPerformed(evt);
            }
        });
        getContentPane().add(txtnilaihuruf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 130, 110, -1));

        txtbobot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtbobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbobotActionPerformed(evt);
            }
        });
        getContentPane().add(txtbobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 170, 110, -1));

        tabelnilai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelnilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelnilai);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 990, 340));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Jenis kelamin");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Cari data Mahasiswa");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 770, -1, -1));

        txtjeniskelamin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtjeniskelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjeniskelaminActionPerformed(evt);
            }
        });
        getContentPane().add(txtjeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 150, -1));

        txtcaridatamhs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtcaridatamhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaridatamhsActionPerformed(evt);
            }
        });
        getContentPane().add(txtcaridatamhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 770, 230, -1));

        btnproses.setText("proses");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });
        getContentPane().add(btnproses, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 280, 110, 30));

        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 860, 140, 40));

        btnsimpan.setText("simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 860, 140, 40));

        btnedit.setText("edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 860, 140, 40));

        btnhapus.setText("hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 860, 140, 40));

        btnkeluar1.setText("keluar");
        btnkeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 860, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcarinilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcarinilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcarinilaiActionPerformed

    private void txtdosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdosenActionPerformed

    private void txtnamamahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamamahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamamahasiswaActionPerformed

    private void txtnomorindukmhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomorindukmhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomorindukmhsActionPerformed

    private void txtketeranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtketeranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtketeranganActionPerformed

    private void txtsksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsksActionPerformed

    private void txtnamamtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamamtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamamtkActionPerformed

    private void txtnilaiangkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnilaiangkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnilaiangkaActionPerformed

    private void txtnilaihurufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnilaihurufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnilaihurufActionPerformed

    private void txtbobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbobotActionPerformed

    private void txtjeniskelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjeniskelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjeniskelaminActionPerformed

    private void txtcaridatamhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaridatamhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaridatamhsActionPerformed

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprosesActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
    bersih();           // TODO add your handling code here:
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed

    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed

    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
     
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnkeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeluar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formnilaimahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formnilaimahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formnilaimahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formnilaimahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new formnilaimahasiswa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(formnilaimahasiswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar1;
    private javax.swing.JButton btnproses;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cmbmtk;
    private javax.swing.JComboBox<String> cmbnidn;
    private javax.swing.JComboBox<String> cmbsmt;
    private javax.swing.JComboBox<String> cmbta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelmhs;
    private javax.swing.JTable tabelnilai;
    private javax.swing.JTextField txtbobot;
    private javax.swing.JTextField txtcaridatamhs;
    private javax.swing.JTextField txtcarinilai;
    private javax.swing.JTextField txtdosen;
    private javax.swing.JTextField txtjeniskelamin;
    private javax.swing.JTextField txtketerangan;
    private javax.swing.JTextField txtnamamahasiswa;
    private javax.swing.JTextField txtnamamtk;
    private javax.swing.JTextField txtnilaiangka;
    private javax.swing.JTextField txtnilaihuruf;
    private javax.swing.JTextField txtnomorindukmhs;
    private javax.swing.JTextField txtsks;
    // End of variables declaration//GEN-END:variables
}
